### ISSUE TITLE
When DefaultGenerator.generate() fails, this is ignored.

### ISSUE THREAD

**Issue by ePaul** [zalando-stups/swagger-codegen-tooling#10]
This might not apply to the latest released version (I didn't try this due to other problems), but it shows when using this project's maven-plugin with the latest master of swagger-codegen.

The the `generate()` method in `io.swagger.codegen.DefaultGenerator` just sets a status flag (in the DefaultGenerator class) when any exception is caught while generating, and CodeGenMojo does not check this flag. (This is similar to [Issue #1140 in swagger-codegen](https://github.com/swagger-api/swagger-codegen/issues/1140)).

So if there is a failure in generating one of the files, the thrown exception gets swallowed, and the maven build still is SUCCESSFUL.

**Comment by jbellmann** [comment]
Hi @ePaul,

I updated to 'swagger-codegen' version 2.1.3 where the 'CodegenStatus' was introduced. This is checked now after codegeneration and throws an exception if 'FAILED'. But it is not possible anymore to get any information about the exception. When I see the code for 'DefaultGenerator' they removed the line with 'e.printStacktrace()' . Maybe we will replace 'DefaultGenerator' with a custom implementation to get all information needed. What do you think?

I released version 0.4.13. Please try the new version and let me know if everything works as expected.

Cheers
Jörg

**Comment by ePaul** [comment]
I guess fixing it at the source is a better idea than copying everything. The swagger-codegen folks seem to be receptive to pull requests.

**Comment by jbellmann** [comment]
I think that was fixed already.
