### ISSUE TITLE
Invalid generation of API query params

### ISSUE THREAD

**Issue by jbadeau** [zalando-stups/swagger-codegen-tooling#22]
Generation of query params for API is incorrect

The output is:
```json  
@RequestParam("filter", required=true) String filter);
```
but should be:
```json
@RequestParam(value="filter", required=true) String filter);
```
the template at:

https://github.com/zalando-stups/swagger-codegen-tooling/blob/master/swagger-codegen-templates/swagger-codegen-template-spring-interfaces/src/main/resources/SpringInterfaces/queryParams.mustache

looks to be the issue:

@RequestParam("filter") String filter); is valid but not if required or default is present then value="" must be used. I would prob just use value ="" all the time.

**Comment by jbellmann** [comment]
@jbadeau thanks for reporting the issue. [0.4.18](https://github.com/zalando-stups/swagger-codegen-tooling/releases/tag/0.4.18) should fix this.
Can you please verify and close the issue if it's working?

Thanks,
Jörg

**Comment by jbadeau** [comment]
Yes I will verify tomorrow 😊

**Comment by jbadeau** [comment]
this issue is now solved. Thank you :)

**Comment by jbellmann** [comment]
You are welcome.
