### ISSUE TITLE
language=spring-interfaces for a yaml with file-upload seems to produce incorrect code

### ISSUE THREAD

**Issue by A-Joshi** [zalando-stups/swagger-codegen-tooling#26]
API with a formupload  and using language = springinterfaces produces incorrect java code. Looks like the code generating FormDataContentDisposition and FormDataParam and also missing the includes for them.

With spring I would have expected mode along the lines of: @RequestPart("file") MultipartFile application

Attached is a zip with yaml and maven pom file to demonstrate the error - just unzip and run mvn clean compile.

[Uploading spring-swagger-error.zip…]()

**Comment by A-Joshi** [comment]
[spring-swagger-error.zip](https://github.com/zalando-stups/swagger-codegen-tooling/files/146738/spring-swagger-error.zip)
 Not sure if the upload worked earlier

**Comment by jbellmann** [comment]
Thank you, I will have a look into this.

**Comment by A-Joshi** [comment]
Hello,

By "borrowing" a some files and lines from the language="spring-mvc" in
the standard swagger-codegen project I was able to get it to work.  My
changes were basically:

Replace the contents of the file:
swagger-codegen-templates/swagger-codegen-template-spring-interfaces/src/main/resources/SpringInterfacesResponseEntityNoSwaggerAnnotations/formParams.mustache
with the contents of:
modules/swagger-codegen/target/classes/JavaSpringMVC/formParams.mustache

and get all the missing imports from:
modules/swagger-codegen/target/classes/JavaSpringMVC/api.mustache


I have not fixed it for all the cases - with/without annotations etc.
Would you like me to fork the repository and checking my changes there?

Regards,

Amit Joshi

**Comment by jbellmann** [comment]
@A-Joshi 

I'm sorry that it takes that long for response from my side. But today, I spend some time to hopefully fix this issue. So, I released 0.4.26 with a fix. It would be nice if you could figure out that it's working for you.

Cheers
Jörg

**Comment by LappleApple** [comment]
Hi @A-Joshi, were you able to make things work? Let us know so we can close out the issue.

**Comment by jbellmann** [comment]
Seems to be working. Reopen if needed.
