### ISSUE TITLE
Allow generating code from an URL

### ISSUE THREAD

**Issue by ePaul** [zalando-stups/swagger-codegen-tooling#29]
The maven-codegen plugin from io.swagger allows generating code from an HTTP URL (of the YAML or JSON definition). This project's plugin doesn't allow this, finishing with an error message instead:

> [ERROR] Failed to execute goal org.zalando.maven.plugins:swagger-codegen-maven-plugin:0.4.24:codegen (generate-nakadi-api) on project tarbela: The 'apiFile' does not exists at : https://raw.githubusercontent.com/zalando/nakadi/nakadi-jvm/api/nakadi-event-bus-api.yaml

Digging into the code, this seems to be caused by the `checkApiFileExists` method in StandaloneCodeGenerator. Commenting out its call in line 83 prevents this error message, and makes the generation work.

Is this check needed for some reason? It looks like the called framework will do a similar check again, but in a way that works for HTTP URLs.

**Comment by jbellmann** [comment]
There is no reason to not allow reading definitions from an URL. I will remove this restriction. Was there to fail fast I would say.
