### ISSUE TITLE
Unable to generate any code using plugin

### ISSUE THREAD

**Issue by muthu8891** [zalando-stups/swagger-codegen-tooling#30]
I tried the approach mentioned in read me. Added the swagger.json file to 'Src/main/resources' folder and ran a 'mvn clean install' after adding the plugin to the Pom.xml. No code got generated. Build is success and jar only gets generated! Is my approach incorrect ? Please guide me...

**Comment by muthu8891** [comment]
[swagger-springboot-codegen.zip](https://github.com/zalando-stups/swagger-codegen-tooling/files/243244/swagger-springboot-codegen.zip)

This is the project for which am trying to generate code. spring-boot based application

**Comment by ePaul** [comment]
The plugin doesn't bind its goals to any life cycle phase. You'll either have to do `mvn swagger-codegen:codegen`, or add an execution entry to the plugin's configuration, binding it to a phase.

```xml
			<plugin>
				<groupId>org.zalando.maven.plugins</groupId>
				<artifactId>swagger-codegen-maven-plugin</artifactId>
				<version>0.4.26</version>
				<executions>
					<execution>
						<id>generate-from-swagger</id>
						<goals>
							<goal>codegen</goal>
						</goals>
						<phase>generate-sources</phase>
					</execution>
				</executions>
				<configuration>
					<apiFile>${project.basedir}/src/main/resources/petstore.json</apiFile>
					<language>jaxrsinterfaces</language>
					<apiPackage>com.yourcompany.api</apiPackage>
					<modelPackage>com.yourcompany.model</modelPackage>
				</configuration>
				<!-- put template-dependency here, directly into plugin -->
				<dependencies>
					<dependency>
						<groupId>org.zalando.stups</groupId>
						<artifactId>swagger-codegen-template-jaxrs-interfaces</artifactId>
						<version>0.4.26</version>
					</dependency>
				</dependencies>
			</plugin>
```
(You can also put the configuration inside the `execution`, in case you want to generate sources from several Swagger files.)

**Comment by muthu8891** [comment]
Thanks Paul, that helped!
