### ISSUE TITLE
Swagger Codegen error with version 0.4.26

### ISSUE THREAD

**Issue by muthu8891** [zalando-stups/swagger-codegen-tooling#31]
Getting the following error while trying to generate spring-boot code with plugin version 0.4.26. The same works for 0.4.22. 
[swagger-springboot-error.zip](https://github.com/zalando-stups/swagger-codegen-tooling/files/244806/swagger-springboot-error.zip)

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building swagger-springboot-codegen 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ swagger-springboot-codegen ---
[INFO] 
[INFO] --- swagger-codegen-maven-plugin:0.4.26:codegen (YAML to code Generation) @ swagger-springboot-codegen ---
[INFO] 'apiFile' seems not be an valid URL, check file exist
[INFO] register config : 'springinterfaces' with class : de.zalando.stups.swagger.codegen.language.SpringInterfaces
[INFO] register config : 'springinterfacesNoSwaggerAnnotations' with class : de.zalando.stups.swagger.codegen.language.SpringInterfacesNoSwaggerAnnotations
[INFO] register config : 'springinterfacesResponseEntity' with class : de.zalando.stups.swagger.codegen.language.SpringInterfacesResponseEntity
[INFO] register config : 'springinterfacesResponseEntityNoSwaggerAnnotations' with class : de.zalando.stups.swagger.codegen.language.SpringInterfacesResponseEntityNoSwaggerAnnotations
[INFO] register config : 'jaxrsinterfaces' with class : de.zalando.stups.swagger.codegen.language.JaxRsInterfaces
[INFO] register config : 'android' with class : io.swagger.codegen.languages.AndroidClientCodegen
[INFO] register config : 'aspnet5' with class : io.swagger.codegen.languages.AspNet5ServerCodegen
[INFO] register config : 'async-scala' with class : io.swagger.codegen.languages.AsyncScalaClientCodegen
[INFO] register config : 'csharp' with class : io.swagger.codegen.languages.CSharpClientCodegen
[INFO] register config : 'dart' with class : io.swagger.codegen.languages.DartClientCodegen
[INFO] register config : 'flash' with class : io.swagger.codegen.languages.FlashClientCodegen
[INFO] register config : 'python-flask' with class : io.swagger.codegen.languages.FlaskConnexionCodegen
[INFO] register config : 'go' with class : io.swagger.codegen.languages.GoClientCodegen
[INFO] register config : 'groovy' with class : io.swagger.codegen.languages.GroovyClientCodegen
[INFO] register config : 'java' with class : io.swagger.codegen.languages.JavaClientCodegen
[INFO] register config : 'jaxrs' with class : io.swagger.codegen.languages.JavaJerseyServerCodegen
[INFO] register config : 'jaxrs-cxf' with class : io.swagger.codegen.languages.JavaCXFServerCodegen
[INFO] register config : 'jaxrs-resteasy' with class : io.swagger.codegen.languages.JavaResteasyServerCodegen
[INFO] register config : 'inflector' with class : io.swagger.codegen.languages.JavaInflectorServerCodegen
[INFO] register config : 'javascript' with class : io.swagger.codegen.languages.JavascriptClientCodegen
[INFO] register config : 'javascript-closure-angular' with class : io.swagger.codegen.languages.JavascriptClosureAngularClientCodegen
[INFO] register config : 'jmeter' with class : io.swagger.codegen.languages.JMeterCodegen
[INFO] register config : 'nodejs-server' with class : io.swagger.codegen.languages.NodeJSServerCodegen
[INFO] register config : 'objc' with class : io.swagger.codegen.languages.ObjcClientCodegen
[INFO] register config : 'perl' with class : io.swagger.codegen.languages.PerlClientCodegen
[INFO] register config : 'php' with class : io.swagger.codegen.languages.PhpClientCodegen
[INFO] register config : 'python' with class : io.swagger.codegen.languages.PythonClientCodegen
[INFO] register config : 'qt5cpp' with class : io.swagger.codegen.languages.Qt5CPPGenerator
[INFO] register config : 'ruby' with class : io.swagger.codegen.languages.RubyClientCodegen
[INFO] register config : 'scala' with class : io.swagger.codegen.languages.ScalaClientCodegen
[INFO] register config : 'scalatra' with class : io.swagger.codegen.languages.ScalatraServerCodegen
[INFO] register config : 'silex-PHP' with class : io.swagger.codegen.languages.SilexServerCodegen
[INFO] register config : 'sinatra' with class : io.swagger.codegen.languages.SinatraServerCodegen
[INFO] register config : 'slim' with class : io.swagger.codegen.languages.SlimFrameworkServerCodegen
[INFO] register config : 'spring-mvc' with class : io.swagger.codegen.languages.SpringMVCServerCodegen
[INFO] register config : 'dynamic-html' with class : io.swagger.codegen.languages.StaticDocCodegen
[INFO] register config : 'html' with class : io.swagger.codegen.languages.StaticHtmlGenerator
[INFO] register config : 'swagger' with class : io.swagger.codegen.languages.SwaggerGenerator
[INFO] register config : 'swagger-yaml' with class : io.swagger.codegen.languages.SwaggerYamlGenerator
[INFO] register config : 'swift' with class : io.swagger.codegen.languages.SwiftCodegen
[INFO] register config : 'tizen' with class : io.swagger.codegen.languages.TizenClientCodegen
[INFO] register config : 'typescript-angular2' with class : io.swagger.codegen.languages.TypeScriptAngular2ClientCodegen
[INFO] register config : 'typescript-angular' with class : io.swagger.codegen.languages.TypeScriptAngularClientCodegen
[INFO] register config : 'typescript-node' with class : io.swagger.codegen.languages.TypeScriptNodeClientCodegen
[INFO] register config : 'akka-scala' with class : io.swagger.codegen.languages.AkkaScalaClientCodegen
[INFO] register config : 'CsharpDotNet2' with class : io.swagger.codegen.languages.CsharpDotNet2ClientCodegen
[INFO] register config : 'clojure' with class : io.swagger.codegen.languages.ClojureClientCodegen
[INFO] register config : 'haskell' with class : io.swagger.codegen.languages.HaskellServantCodegen
[INFO] register config : 'lumen' with class : io.swagger.codegen.languages.LumenServerCodegen
[INFO] Generate for language : springinterfaces
[INFO] reading from D:/PLATFORMS/Micro-Services/micro-ws/swagger-springboot-codegen/src/main/resources/swagger.yaml
[INFO] writing file D:\PLATFORMS\Micro-Services\micro-ws\swagger-springboot-codegen\target\generated-sources\swagger-codegen/com\example\test\api\model\Greeting.java
[ERROR] SpringInterfaces\model_doc.mustache (The system cannot find the path specified)
[ERROR] can't load template SpringInterfaces\model_doc.mustache
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.489 s
[INFO] Finished at: 2016-05-02T15:18:33+05:30
[INFO] Final Memory: 17M/212M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.zalando.maven.plugins:swagger-codegen-maven-plugin:0.4.26:codegen (YAML to code Generation) on project swagger-springboot-codegen: Could not generate model 'Greeting': can't load template SpringInterfaces\model_doc.mustache -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by jbellmann** [comment]
@muthu8891 
I corrected your project:

[swagger-springboot-codegen.zip](https://github.com/zalando-stups/swagger-codegen-tooling/files/247004/swagger-springboot-codegen.zip)

Some hints:
- do not put extracted templates in your 'src/main/resources'-folder
- add the template-dependency not as a 'compile'-dependency, instead add it as dependency to the plugin itself
