### ISSUE TITLE
Usage of Spring MVC interfaces

### ISSUE THREAD

**Issue by ethlo** [zalando-stups/swagger-codegen-tooling#32]
Hi, I was inspired to do some hacking around in Spring MVC interface generation in the hope that I could use this to generate nicely separated interfaces holding all annotations, (request-mapping, security, etc), only later to learn that method level annotations are not inherited, and Spring MVC will not detect any of the controllers, `@Secured` annotations, etc. This leads me to ask, what is the "spring-interfaces" templating used for? Thanks you for you time! :)

Refs:
- http://stackoverflow.com/questions/8002514/spring-mvc-annotated-controller-interface

**Comment by jbellmann** [comment]
So for a quick response:
Please take the corrected zip-file from #31, unzip and import into IDE without running maven on that project. You only should see the 'App' and 'GreeterImpl' in 'src/main/java'. Then run 'mvn clean install', generation starts, compiling should pass and the only test that requests the 'GreeterImpl'-Controller should also pass.

You will find the sources in 'target/generated-sources/swagger-codegen' have a look into 'GreeterApi'.

Try out. Let me know when it is not working.
I'm not sure about `@Secure` because I never tried that.

**Comment by ethlo** [comment]
Thanks for you reply I had look as you told me, and I did not imply that the code generation does not work, that is all good. My problem was that Spring did not pick up the controllers. In you example it works, but as soon as you introduce other annotations like `@Secured` and probably `@Transactional` as well that generates proxies, the annotations will get lost as there is no method level annotation inheritance in Java. I have been successful so far in using abstract classes instead, which is fine for me as there is rarely a need to extend from anything else in a controller anyway.

**Comment by jbellmann** [comment]
Hi Morten, you are right, there are problems with method-level annotation (e.g. annotations for parameter). But for most cases it's working and the IDE seems to be aware of this and generates these annotations too when you hit 'add unimplemented methods' (maybe in Eclipse).
The intention for this was to get rid off all these Swagger-API-Annotations. 20 lines of annotations, one line of controller-code. I was not able to see what the controller is really doing. That's better now and working.
If you think abstract classes are a better way, maybe you provide an PR where you toggle between interface-generation and generation of abstract classes, or at least open an issue for such an feature. Then we will think about it and if I have some time will implement that, if possible ;-)

Cheers,
Jörg

**Comment by ethlo** [comment]
Sure, I will pay it back in the form of a PR later 👍

**Comment by ePaul** [comment]
A possibly better way would be to generate a whole (non-abstract) controller class with all the annotations, which delegates the methods to an also-generated (but non-annotated) service interface, which can then be implemented by user code.

**Comment by LappleApple** [comment]
Hi @ethlo, are you still interested in creating a PR on this? Just let us know...

**Comment by ender74** [comment]
I did create a pull request.

**Comment by jbellmann** [comment]
@ethlo great, I will have a look into it.

**Comment by LappleApple** [comment]
Hi @jbellmann, do you plan to review @ender74's PR anytime soon?

**Comment by jbellmann** [comment]
All PR merged an closed. So everything should be in place.
