### ISSUE TITLE
Gradle plugin status/version

### ISSUE THREAD

**Issue by sovereign36** [zalando-stups/swagger-codegen-tooling#33]
Hi, 

I was trying to follow the README to configure the Gradle plugin, which gives me this error : 
` > Could not resolve all dependencies for configuration ':classpath'. > Could not find org.zalando.stups:swagger-codegen-gradle-plugin:0.4.24.`

Thus I'm interested if I'm missing some configuration or plugin is just not yet published? 
If it is not, I would be very interested if there's any work planned on it in the near future? 

Thanks

**Comment by jbellmann** [comment]
You did everything fine. I got the same error ;-)

I will fix that, seems not to be published. I have no clue why. Will do again today.

**Comment by jbellmann** [comment]
[There it is](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22swagger-codegen-gradle-plugin%22)

But keep in mind that I'm not an expert in writing gradle-plugins. So you will probably find bugs. But then, please report them.

Thanks
