### ISSUE TITLE
custom mustache template

### ISSUE THREAD

**Issue by jkerak** [zalando-stups/swagger-codegen-tooling#38]
is there an example of how I can point my code generation (in my case for jax-rs) to a local mustache template? I'm looking to add JSR303 annotations to the template.

**Comment by jbellmann** [comment]
[Here is ](https://github.com/zalando-stups/swagger-codegen-tooling/blob/master/swagger-codegen-templates/swagger-codegen-template-spring-interfaces/src/main/resources/SpringInterfaces/model303.mustache) a template for that.

[Here is ](https://github.com/zalando-stups/swagger-codegen-tooling/blob/master/swagger-codegen-templates/swagger-codegen-template-spring-interfaces/src/main/java/de/zalando/stups/swagger/codegen/language/SpringInterfaces.java#L58) the 'switch' enabled.

**Comment by jkerak** [comment]
I understand that JSR303 are supposed to be supported SpringMVC (though min/max don't seem to currently work), but I was looking to create one for JAX-RS with JSR303. Any particular reason it isn't supported currently?

**Comment by jbellmann** [comment]
To be honest, I don't use JAX-RS. So I don't invest time in JAX-RS. But you can contribute if you want to.

Regards

**Comment by LappleApple** [comment]
Hi @jkerak, are you interested in contributing this? Let us know and we'll add an "In Progress" label to the issue.

**Comment by jkerak** [comment]
Hi @LappleApple I'll close for now - don't have the cycles. I'll open a new more specific one if I get the chance to take a look.
