### ISSUE TITLE
Inverted Spring MVC query param required generation

### ISSUE THREAD

**Issue by BGehrels** [zalando-stups/swagger-codegen-tooling#40]
Spring MVCs `@RequestParam` annotation has an attribute `required`. It is, by default, `true`.
The behaviour of SpringInterfacesNoSwaggerAnnotations/queryParams.mustache is therefore broken:

If a query parameter is required, it generates `required=true`, which is superfluous. If a query parameter is not required, it generates no required parameter at all. The default value will take it's place then, which is `true` - that is just wrong.

The same seems to be true for the other SpringInterface\* templates.

**Comment by jbellmann** [comment]
@BGehrels 
please try out release `0.4.29`. If this is fixed, close this issue or report your observations please.

**Comment by jbellmann** [comment]
Seems to be working. Reopen if needed.
