### ISSUE TITLE
Do not generate consumes for requests without body

### ISSUE THREAD

**Issue by BGehrels** [zalando-stups/swagger-codegen-tooling#41]
If you define something like

```
consumes: application/json
```

on top of your swagger file and then generate Spring MVC controller interfaces for a 

```
GET /myResource
```

endpoint, the following annotation will be generated: 

```
@RequestMapping(value="/purchase-orders", method=RequestMethod.GET , consumes={ "application/json" })
```

The Spring docs say about consumes:

> The format is a single media type or a sequence of media types, with a request only mapped if the Content-Type matches one of these media types.

And Spring is pretty strict here: if the Content-Type header is missing, it will return a 400 status code. This does not seem to be what we want here: Defining a Content-Type header without sending a request body makes no sense, and GET requests are not meant to have a request body. So i guess, it is better to just leave this out for methods without body.

**Comment by ePaul** [comment]
I would say you should not use `consumes: application/json` at the top level of your file, just for this reason.
But yes, the consumes property obviously only applies to operations which have a request body.

**Comment by jbellmann** [comment]
@BGehrels 
I agree with @ePaul here.

But try out version `0.4.30`. Let me know about issues with that version or close this issues if you think it's fixed.

**Comment by jbellmann** [comment]
Seems to me everything working as expected? Reopen if needed.
