### ISSUE TITLE
apiPackage required even when skipApigeneration defined

### ISSUE THREAD

**Issue by kkrauth** [zalando-stups/swagger-codegen-tooling#44]
When `<skipApigeneration>true</skipApigeneration>` is set, the `<apiPackage>` value is still required. When omitted, a NullPointerException is thrown. Ideally `<apiPackage>` should be optional when skipping API generation. Using version 0.4.30.

**Comment by jbellmann** [comment]
Thanks for reporting, will look into this.

**Comment by jbellmann** [comment]
@kkrauth 
Could you please verify that 0.4.31 works for you as expected?

Regards
Jörg

**Comment by kkrauth** [comment]
Yep, that fixed it. Thanks! 👍
