### ISSUE TITLE
Rename generated Controller-classes from *Impl to *Controller to not

### ISSUE THREAD

**Issue by jbellmann** [zalando-stups/swagger-codegen-tooling#52]
... be confused what is a Controller, what is an Implemenation oft the generated api.

**Comment by jbellmann** [comment]
@ender74 What do you think? I have seen the controllers generated name ends with 'Impl'. Would it be fine to you when I rename it to 'Controller' instead?

Regards
Jörg

**Comment by ender74** [comment]
Yes, good idea. The suffix Controller is better.
