### ISSUE TITLE
Re-enable gradle plugin

### ISSUE THREAD

**Issue by otrosien** [zalando-stups/swagger-codegen-tooling#58]
Ensure same feature set to re-align the gradle plugin with the maven plugin.

framework:
:white_check_mark: ensure gradle 2.10+ and gradle 3 compatibility (is that sufficient?)
:white_check_mark: java

feature set:
:white_check_mark: use single input file instead of a source set as swagger source definition
❓ : apply same defaults as the maven plugin
:white_check_mark: ensure interoperability with compile phase

testing:
:white_check_mark: smoke test using gradle testKit
:white_check_mark: at least one unit test for critical path

releasing:
🚧 release 0.4.38 to the gradle plugin portal

**Comment by otrosien** [comment]
Here is the current work-in-progress: 

https://github.com/otrosien/swagger-codegen-gradle-plugin2

**Comment by otrosien** [comment]
gradle and maven seem to write to different locations in the yamltojson use case. @jbellmann could you clarify what's the use case and the desired output directory?

**Comment by jbellmann** [comment]
@otrosien sure, I can :-)

We mostly define apis in yaml. The swagger-ui instead expects a json to be served for rendering. That's the reason for a yaml->json transformation. So if you want your application to expose an swagger-ui-endpoint that the way to go.

Have a look [into this module](https://github.com/zalando-stups/swagger-codegen-tooling/tree/master/spring-boot-stups-swagger-codegen-ui) to get an idea.

**Comment by jkerak** [comment]
Is there any update to this? https://github.com/zalando-incubator/swagger-codegen-gradle-plugin no longer exists

**Comment by otrosien** [comment]
There has been a cleanup process in zalando-incubator, and this work-in-progress was part of the removal. Unfortunately I didn't succeed in pushing the official swagger-codegen project towards integrating a gradle project. There has been lots of discussion without outcome. ( https://github.com/swagger-api/swagger-codegen/issues/4758 )
