### ISSUE TITLE
Introduce something like skipApiGeneration to be used as plugin config

### ISSUE THREAD

**Issue by SunriseJJJ** [zalando-stups/swagger-codegen-tooling#6]
It will be really nice if i can skip generation of API classes as well as model classes (using skipModelgeneration property) e.g. when i want to re-create only model when only definitions was changed in my contract but already have API classes generated and saved somewhere (probably as another module)/

**Comment by jbellmann** [comment]
Please try out 0.4.8. If it does not work for you, reopen this issue.
