### ISSUE TITLE
Evaluate official maven plugin for swagger-codegen 

### ISSUE THREAD

**Issue by otrosien** [zalando-stups/swagger-codegen-tooling#61]
In best case this project can be reduced to publishing our own code templates, and letting swagger's own maven plugin do the code generation.

## Questions to answer

❓ what features does our maven integration offer that the official plugin does not?
✅  is the official plugin capable of using our templates or do we need to adapt something?
❓ do we need to offer some migration guide how to switch to the official plugin?
❓ how do our templates perform in comparison with the current official (e.g. spring) code templates?

See 
* https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen-maven-plugin
* https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/JavaSpring

**Comment by cfraenkel** [comment]
The main reason for using this plugin were the templates you provide:
The project I'm developing is using a contract first approach. From my tests the code templates provided by this project are far better suited to this - I do not have any need to generate any springfox (or even swagger) annotated code (I do serve the swagger spec I'm developing against). 
I also like that the templates do not generate poms or other (for me) unimportant files as this allows me to generate the interfaces on each build from the spec.

I've tried to run your templates with the official codegen but this was not that simple - I encountered  dependencies on swagger-codegen-common and other problems while trying that (can't remember the details, it's been a while)

From what I've seen the official templates are adding bean validation support. Comprehensive bean validation support is a feature that would be great in your templates too ( I know there is some support already)

**Comment by otrosien** [comment]
Thanks for your feedback. We will take it into consideration when deciding how to proceed next.

**Comment by otrosien** [comment]
Just verified our current 0.5.0-SNAPSHOT against the 2.2.1 swagger-codegen-cli.jar:

```
java -cp ~/.m2/repository/org/zalando/stups/swagger-codegen-common/0.5.0-SNAPSHOT/swagger-codegen-common-0.5.0-SNAPSHOT.jar:/Users/otrosien/.m2/repository/org/zalando/stups/swagger-codegen-template-spring-interfaces/0.5.0-SNAPSHOT/swagger-codegen-template-spring-interfaces-0.5.0-SNAPSHOT.jar:swagger-codegen-cli.jar io.swagger.codegen.SwaggerCodegen generate  -l springinterfaces -i http://petstore.swagger.io/v2/swagger.json -o zalando
```

... works.
