### ISSUE TITLE
spring interface api files fail to compile symbol not found @FormParam

### ISSUE THREAD

**Issue by A-Joshi** [zalando-stups/swagger-codegen-tooling#9]
The generated spring interface api files do not compile with an error:

[ERROR] <filename> error: cannot find symbol
[ERROR] symbol:   class FormParam

The reason is because  the generated file does not contain the includes:

import javax.ws.rs._;
import javax.ws.rs.core._;

For now I fixed it by adding the two includes to the top of the file:
swagger-codegen-templates/swagger-codegen-template-spring-interfaces/src/main/resources/SpringInterfaces/api.mustache 
but am not sure if that is the correct approach should be added somewhere else.

Happens with Java 1.8 not sure if it happens with earlier versions.

$ java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

**Comment by jbellmann** [comment]
Thanks for reporting the issue. I will have a look at this.

**Comment by jbellmann** [comment]
Hi @A-Joshi,
can provide your 'api.yaml' or an snippet for testing, please?

**Comment by jbellmann** [comment]
@A-Joshi , do you want to use JAX-RS ? Then maybe you should try out 'jaxrsinterfaces' as language. Then also interfaces will be generated with JAX-RS imports. Have a look at the Integration-Tests for maven-plugin [here](https://github.com/zalando-stups/swagger-codegen-tooling/blob/master/swagger-codegen-maven-plugin/src/it/spring-boot-jersey/pom.xml).

**Comment by A-Joshi** [comment]
I am looking at Jax RS too. I can't seem to upload a sample project here for testing.

**Comment by jbellmann** [comment]
@A-Joshi 

Please can you describe the problem again. I didn't get it, sorry. When you try to generate 'SpringInterfaces' as it seems to me when I read the first comment, then no imports of 'javax.ws.rs.*' should be used. Spring has it's own form-handling and do not depend on 'javax.ws.rs' in anyway. At least in my experience with spring.

Otherwise I will close this issue in 2 weeks if no response will arrive.

**Comment by LappleApple** [comment]
@jbellmann closing out this issue as per your last comment from 2015
